config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user, ->(user) { user.role?(:admin) } do
      root to: 'admin/dashboard#index', as: :admin_root
    end

    authenticated :user, ->(user) { user.role.is_public? } do
      root 'base/private/profiles#show', as: :authenticated_root
    end

    root to: 'devise/sessions#new'

    get 'users/password/recover' => 'users/passwords#password_recover_instructions', as: :recover
    post 'users/auth/registration' => 'users/omniauth_callbacks#create', as: :user_omniauth_register
    get 'admin/sign_in' => 'devise/sessions#new'
  end

  namespace :admin do
    post 'artists/featured_update' => 'artists#featured_update'
    post 'gigs/featured_update' => 'gigs#featured_update'
    resources :features, :dashboard, :artists, :gigs
  end

  scope module: :base do
    scope module: :public, as: :public do
      resources :profiles, only: :show, param: 'profile_id'
      resources :profiles, only: [] do
        resources :events, :awards, only: :index
        resources :gigs, only: :index
        resource :press_kit, only: :show
        resources :photo_albums, path: 'gallery', only: [:index, :show]
        resources :bookings, only: [:index, :create] do
          collection do
            post 'new_gig' => :create_new_gig, as: :create_new_gig
          end
        end
        resources :booking_steps
        resources :artists, only: :index
        resources :releases, only: :index
      end
    end

    scope module: :private, as: :private do
      resource :profiles, only: [:show, :update], path: '', as: :profile do
        patch :update_photo
        resource :press_kit, only: :show
      end

      resources :gigs, except: [:show, :destroy] do
        collection do
          delete :destroy
        end
      end

      resources :events, except: [:show, :destroy] do
        collection do
          delete :destroy
        end
      end

      resources :photo_albums, except: :destroy, path: 'gallery' do
        collection do
          delete :destroy
        end
      end

      resources :releases, path: 'music' do
        collection do
          get :list
        end
      end

      resources :awards, except: :destroy do
        collection do
          delete :destroy
        end
      end

      resources :artists, only: :index

      resources :bookings, only: :index do
        member do
          put ':status' => :state, constraints: { status: /confirmed|rejected/ }, as: :status
          post 'request' => :request_confirmation
          patch 'cancel' => :cancel_booking_request
        end
      end
    end

    scope module: :resources do
      resources :gigs, :events, only: :show
      resources :comments, only: :create
      resource :settings, only: [:show, :update]
      resources :conversations, only: [:index, :show, :destroy] do
        collection do
          get ':recipient_id/new' => :new, as: :new
          post ':recipient_id/create' => :create, as: :create
        end
        member do
          post :update
        end
      end
      resources :notifications, only: [:index, :show, :destroy]
      resources :photos, only: [:create, :destroy] do
        member do
          put 'crop/:preset' => 'photos#crop', as: :crop, constraints: { preset: /event_photo|avatar|wallpaper/ }
        end
      end
      resources :songs, only: [:create, :destroy] do
        member do
          put :publish
        end
      end
      resources :payments, path: 'payments', only: :index do
        collection do
          get 'event/:id' => :event_form, as: :ticket
          post 'event/:id' => :event_charge
        end
      end
    end
  end

  scope module: :guests do
    get ':page' => 'static_pages#index', as: :static_page, constraints: { page: /terms|faq|privacy|contact/ }

    resources :subscriptions, only: :create

    resources :search, only: :index, shallow_path: 'search' do
      collection do
        get ':resource' => :search, as: :resource, constraints: { resource: /artist|label|venue|producer|manager/ }
        get :event
      end
    end

    resources :discovery, only: [] do
      collection do
        get ':resource' => :resource, constraints: { resource: /artists|labels|managers|producers|venues/ }, as: ''
        get :gigs, :events, :music
      end
    end


    ###### without login booking
    resources :profiles, only: :show, param: 'profile_id'
    resources :profiles, only: [] do
      resources :bookings, only: [:index, :create] do
        collection do
          post 'new_gig' => :create_new_gig, as: :create_new_gig
        end
      end
      resources :artists, only: :index
      resources :releases, only: :index
    end
    #####


  end
end

app/controllers/base/resources/payments_controller.rb
module Base
  module Resources
    class PaymentsController < Resources::BaseController
      before_action :set_publishable_key, only: :event_form

      SEARCH_ATTRIBUTES = %w(created_at_gteq created_at_lteq charge_id_cont)

      def index
        @q = current_user.orders.ransack(search_params)
        @orders = @q.result.page(params[:page]).per(20)
      end

      def event_form
        @event = Event.find(params[:id]).decorate
        gon.price = @event.price
      end

      def event_charge
        event = Event.find(params[:id])
        result = TicketChargeService.call(current_user, event, params[:ticket_count], params[:stripe_token])
        if result.success?
          redirect_to({ action: :index }, notice: 'Operation completed successfully')
        else
          redirect_to({ action: :event_form }, alert: result.message)
        end
      end

      private

      def set_publishable_key
        gon.stripe_publishable_key = Rails.application.secrets.stripe['publishable']
      end

      def search_params
        params[:q] && params[:q].permit(SEARCH_ATTRIBUTES)
      end
    end
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
  CREDIT_CARDS = %w(express discover maestro mastercard visa)

  def credit_cards_list
    content_tag(:ul, class: 'payments clearfix') do
      CREDIT_CARDS.each do |credit_card|
        li_content = link_to(image_tag("pay/#{credit_card}.png"), 'javascript: void(0)', class: 'payments_link')
        concat content_tag(:li, li_content, class: 'payments_list')
      end
    end
  end
end

app/views/base/resources/payments/blocks/_form.html.slim
= form_tag('#', id: 'stripe-info-form', data: { 'errors-messages-disabled' => true }) do
  .row
    .col-xs-12
      h3.head_settings Billing information
  .row
    .col-sm-12
      .form-group
        = text_field_tag('name', nil, class: 'form-control', placeholder: 'Full Name', data: { stripe: 'name' })
  .row
    .col-xs-12
      .form-group
        = text_field_tag('address_line1', nil, class: 'form-control', placeholder: 'Address', data: { stripe: 'address_line1' })
  .row
    .col-sm-6
      .form-group
        = text_field_tag('address_country', nil, class: 'form-control', placeholder: 'Country', data: { stripe: 'address_country' })
    .col-sm-6
      .form-group
        = text_field_tag('address_state', nil, class: 'form-control', placeholder: 'State / Province', data: { stripe: 'address_state' })
  .row
    .col-sm-6
      .form-group
        = text_field_tag('address_city', nil, class: 'form-control', placeholder: 'City', data: { stripe: 'address_city' })
    .col-sm-3
      .form-group
        = text_field_tag('address_zip', nil, class: 'form-control', placeholder: 'Zip Code', data: { stripe: 'address_zip' })
  .row
    .col-xs-12
      h3.head_settings Payment information
  .row
    .col-xs-12
      = credit_cards_list
  .row
    .col-sm-12
      .form-group
        = text_field_tag('name', nil, class: 'form-control', placeholder: 'Full Name', data: { stripe: 'name' })
  .row
    .col-sm-6
      .form-group
        = text_field_tag('number', nil, class: 'form-control', placeholder: 'Card number', data: { stripe: 'number', required: true })
    .col-sm-3
      .form-group
        = text_field_tag('cvc', nil, class: 'form-control', placeholder: 'CVC', data: { stripe: 'cvc', required: true })
  .row
    .col-lg-2.col-sm-3
      p.light-gray.p-t7 Card expiration
    .col-lg-4.col-sm-3
      .form-group
        = select_month(nil, { prompt: 'Month' }, class: 'form-control', data: { stripe: 'exp-month', required: true }, placeholder: 'Month')
    .col-sm-3
      .form-group
        = text_field_tag(:year, nil, class: 'form-control', placeholder: 'Year', data: { stripe: 'exp-year', required: true })
  .row
    .col-xs-12
      .b-Top.p-t20.clearfix.m-tb20
        .clearfix
          .pull-sm-left
            label.cb-checkbox.m-t5
              = check_box_tag(:terms, nil, false, data: { required: true })
              ' By clicking the Purchase Button you agree to our
              = link_to 'Terms & Conditions', static_page_path(:terms)
          .pull-sm-right
            p.pull-left.p-t5.m-r5.bold.middleSize
              | Total: $
              span#price
                = @event.price
        .pull-sm-right
          .goods.pull-left
            input.goodsQuantity#quantity type="text" value="1"
            button.incrementGoods
              i.fa.fa-sort-desc
            button.decrementGoods
              i.fa.fa-sort-asc
          button.btn.btn-primary type="submit" Order Now
= form_tag(ticket_payments_path(@event), method: :post, class: 'hidden', id: 'stripe-token-form') do
  input type="hidden" name="stripe_token"
  input type="hidden" name="ticket_count"
- javascript 'https://js.stripe.com/v2/', 'controllers/users/validation.dep', 'utils/notification', 'controllers/base/payments/stripe'

app/views/base/resources/payments/blocks/_resource.html.slim
.row
  .col-xs-12
    h2.head_text.b-Bottom.p-b20
      ' Complete order:
      span.color_green Buy ticket
.row
  .col-xs-12
    .mobile-center.clearfix
      .promo_more.mobile-center.gigs.clearfix
        .promo-logo-now
          = link_to image_tag(resource.photo.url, class: 'mobile-center'), event_path(resource)
        h4.static-content.m-t5
          = resource.title
        .eventName.mobile-center
          p
            i.icon-dark-calendar
            = resource.period
          p
            i.icon-dark-place
            = resource.location.address
          p
            i.icon-dark-money
            | $ #{format("%.2f", resource.price)}