config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user, ->(user) { user.role?(:admin) } do
      root to: 'admin/dashboard#index', as: :admin_root
    end

    authenticated :user, ->(user) { user.role.is_public? } do
      root 'base/private/profiles#show', as: :authenticated_root
    end

    root to: 'devise/sessions#new'

    get 'users/password/recover' => 'users/passwords#password_recover_instructions', as: :recover
    post 'users/auth/registration' => 'users/omniauth_callbacks#create', as: :user_omniauth_register
    get 'admin/sign_in' => 'devise/sessions#new'
  end

  namespace :admin do
    post 'artists/featured_update' => 'artists#featured_update'
    post 'gigs/featured_update' => 'gigs#featured_update'
    resources :features, :dashboard, :artists, :gigs
  end

  scope module: :base do
    scope module: :public, as: :public do
      resources :profiles, only: :show, param: 'profile_id'
      resources :profiles, only: [] do
        resources :events, :awards, only: :index
        resources :gigs, only: :index
        resource :press_kit, only: :show
        resources :photo_albums, path: 'gallery', only: [:index, :show]
        resources :bookings, only: [:index, :create] do
          collection do
            post 'new_gig' => :create_new_gig, as: :create_new_gig
          end
        end
        resources :booking_steps
        resources :artists, only: :index
        resources :releases, only: :index
      end
    end

    scope module: :private, as: :private do
      resource :profiles, only: [:show, :update], path: '', as: :profile do
        patch :update_photo
        resource :press_kit, only: :show
      end

      resources :gigs, except: [:show, :destroy] do
        collection do
          delete :destroy
        end
      end

      resources :events, except: [:show, :destroy] do
        collection do
          delete :destroy
        end
      end

      resources :photo_albums, except: :destroy, path: 'gallery' do
        collection do
          delete :destroy
        end
      end

      resources :releases, path: 'music' do
        collection do
          get :list
        end
      end

      resources :awards, except: :destroy do
        collection do
          delete :destroy
        end
      end

      resources :artists, only: :index

      resources :bookings, only: :index do
        member do
          put ':status' => :state, constraints: { status: /confirmed|rejected/ }, as: :status
          post 'request' => :request_confirmation
          patch 'cancel' => :cancel_booking_request
        end
      end
    end

    scope module: :resources do
      resources :gigs, :events, only: :show
      resources :comments, only: :create
      resource :settings, only: [:show, :update]
      resources :conversations, only: [:index, :show, :destroy] do
        collection do
          get ':recipient_id/new' => :new, as: :new
          post ':recipient_id/create' => :create, as: :create
        end
        member do
          post :update
        end
      end
      resources :notifications, only: [:index, :show, :destroy]
      resources :photos, only: [:create, :destroy] do
        member do
          put 'crop/:preset' => 'photos#crop', as: :crop, constraints: { preset: /event_photo|avatar|wallpaper/ }
        end
      end
      resources :songs, only: [:create, :destroy] do
        member do
          put :publish
        end
      end
      resources :payments, path: 'payments', only: :index do
        collection do
          get 'event/:id' => :event_form, as: :ticket
          post 'event/:id' => :event_charge
        end
      end
    end
  end

  scope module: :guests do
    get ':page' => 'static_pages#index', as: :static_page, constraints: { page: /terms|faq|privacy|contact/ }

    resources :subscriptions, only: :create

    resources :search, only: :index, shallow_path: 'search' do
      collection do
        get ':resource' => :search, as: :resource, constraints: { resource: /artist|label|venue|producer|manager/ }
        get :event
      end
    end

    resources :discovery, only: [] do
      collection do
        get ':resource' => :resource, constraints: { resource: /artists|labels|managers|producers|venues/ }, as: ''
        get :gigs, :events, :music
      end
    end


    ###### without login booking
    resources :profiles, only: :show, param: 'profile_id'
    resources :profiles, only: [] do
      resources :bookings, only: [:index, :create] do
        collection do
          post 'new_gig' => :create_new_gig, as: :create_new_gig
        end
      end
      resources :artists, only: :index
      resources :releases, only: :index
    end
    #####


  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  SAFE_SCOPES = %w(started pending past)

  include Ownable
  include Locationable
  include Indexable

  paginates_per 10

  acts_as_commentable

  has_many :gigs, dependent: :nullify
  has_many :artists, through: :gigs
  belongs_to :photo, class_name: 'Event::Photo'
  has_many :category_categorizable, as: :categorizable
  has_many :category, through: :category_categorizable

  scope :upcoming, -> { where('finished_at > ?', Date.today).order(:started_at) }
  scope :started, -> { where('started_at < :today and finished_at > :today', today: Date.today) }
  scope :pending, -> { where('started_at > ?', Date.today) }
  scope :past, -> { where('finished_at < ?', Date.today) }
  scope :at_date, ->(date) { where('started_at < :date and finished_at > :date', date: date) }
  scope :since_date, ->(date) { where('started_at >= :date', date: date) }

  validates :title, :description_text, :started_at, :finished_at, :photo, presence: true

  def self.with_status(status)
    if SAFE_SCOPES.include? status
      send(status)
    else
      all
    end
  end

  def past?
    finished_at.to_date < Date.today
  end
end

app/models/event/photo.rb
class Event
  class Photo < ::Photo
    def presets
      {
        standard: '200x200',
        medium: '200x127#',
        cropped: "#{crop_w}x#{crop_h}+#{crop_x}+#{crop_y}",
        mini_autocomplete: '40x40#',
        big_autocomplete: '260x200#'
      }
    end
  end
end

app/controllers/base/private/events_controller.rb
module Base
  module Private
    class EventsController < Private::BaseController
      include LocationProcessing

      before_action :authorize_event, only: [:index, :new, :create, :destroy]
      before_action :set_event, only: [:edit, :update]

      def index
        @events = policy_scope(Event).with_status(params[:filter]).page(params[:page])
      end

      def new
        @event = Event.new
        @event_categories = Category.where(category_type: "events")
      end

      def create
        @event = Event.new(event_params) do |event|
          event.owner_profile = @profile
          event.location = find_or_create_location
        end
        @event.save
        respond_with @event, location: private_events_path
      end

      def edit
      end

      def update
        @event.attributes = event_params
        @event.location = find_or_create_location
        @event.save
        respond_with @event, location: private_events_path
      end

      def destroy
        @profile.delete_events(destroy_events_params)
        redirect_to action: :index
      end

      private

      def authorize_event
        authorize Event
      end

      def event_params
        params.require(:event).permit(policy(Event).permitted_attributes)
      end

      def set_event
        @event = Event.find(params[:id])
        authorize @event
      end

      def destroy_events_params
        params.require(:event_ids)
      end
    end
  end
end

app/controllers/base/resources/events_controller.rb
module Base
  module Resources
    class EventsController < Resources::BaseController
      def show
        @event = Event.find(params[:id])
        @comments = @event.comments.recent.all
      end
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
  DATE_FORMAT = '%b %d, %Y'
  GROUP_DATE_FORMAT = '%B %d, %Y'

  def events_caption
    if @profile.user.role?(:label)
      'Upcoming events'
    else
      'My upcoming events'
    end
  end

  def photo_with_promo_logo(model, link)
    distance = get_distance(model.started_at, model.finished_at)
    content_tag :div, class: "promo-logo-#{distance[:class] || :now}" do
      link_to link do
        concat image(model)
        concat content_tag :div, distance[:label], class: "logo-#{distance[:class]}" if distance[:label]
      end
    end
  end

  def image(model)
    image_tag model.photo.with_presets([:cropped, :medium]), class: 'mobile-center'
  end

  def big_date(date)
    content_tag :div, class: 'eventDate w-sm-30 w-xs-45' do
      concat number_span(date.day)
      concat content_tag :h4, Date::MONTHNAMES[date.month], class: 'm-t5'
      concat content_tag :h4, date.year
    end
  end

  def without_filters?
    params[:q].nil? || params[:q].values.try(:join).blank?
  end

  def grouped_events
    @events.pending.group_by(&:started_at) if without_filters?
  end

  def formatted_date(date)
    date.strftime(GROUP_DATE_FORMAT)
  end

  def events_today
    @events.started
  end

  def events_tomorrow
    @events.at_date(Date.tomorrow)
  end

  def status(model)
    to_start = distance_of_time_in(from: model.started_at)
    to_finish = distance_of_time_in(to: model.finished_at)

    case
    when to_finish < 0
      :past
    when to_start >= 0
      :started
    else
      :pending
    end
  end

  def period(model)
    dates = []
    dates << model.started_at.strftime(DATE_FORMAT)
    dates << model.finished_at.strftime(DATE_FORMAT)
    dates.join(' - ')
  end

  private

  def number_span(number)
    content_tag :h4 do
      content_tag :span, number
    end
  end
end

app/views/base/private/events/blocks/_event.html.slim
.gallery.mobile-center.clearfix.main-events
  .col-xs-12
    .mobile-center.gallery-mainFoto
      label.mobile-center.cb-checkbox
        = check_box_tag 'event_ids[]', event.id
    .promo_more.mobile-center.gigs.clearfix
      .promo-logo-now
        = link_to 'javascript: void(0)' do
          = image_tag event.photo.with_presets([:cropped, :medium]), class: 'mobile-center'
      h4.static-content
        = event.title
      .eventName.mobile-center
        p
          i.icon-dark-calendar
          = period(event)
        p
          i.icon-dark-place
          = get_address(event.location)
        p
          i.icon-dark-money>
          | $ #{format("%.2f", event.price)}
    .gallerySettings
      ul
        li
          = link_to edit_private_event_path(event)
            i.icon-changes
        li
          a href="javascript: void(0)"
            i.icon-deleteGallery
    = render 'base/private/events/blocks/status', status: status(event)

app/views/base/private/events/blocks/_form.html.slim
.row
  .col-xs-12
    .well.create-event
      - if event.photo.blank?
        i.fa.fa-picture-o
      button.btn.btn-primary#upload-button Upload image
      - if event.photo.blank?
        p.create-event-text Png, jpg
= file_field_tag 'photo[attachment]', id: 'upload', class: 'hidden'

= simple_form_for [:private, event] do |form|
  = form.input :photo_id, input_html: { class: 'hidden', data: { required: true, 'required-message' => 'Please, upload image' } }
  .row
    .col-xs-12
      h3.head_settings Main information
  .row
    .col-sm-2
      p.text-color.p-t7 Type
    .col-sm-2
      = form.association :category, prompt: 'Select event type', collection: @event_categories, include_blank: false, label: false, input_html: {multiple: false, 'data-required' => true}
  .row
    .col-xs-12
      .form-group
        = form.input :title, input_html: { placeholder: 'Title', class: 'form-control', data: { required: true } }
  = render partial: 'base/blocks/location_autocomplete', locals: { location: event.location }
  .row
    .col-xs-12
      .form-group
        = form.input :description_text, as: :text, input_html: { class: 'editor form-control', rows: 10, data: { required: true } }
  .row.m-t10#date-start
    .col-sm-2
      p.text-color.p-t7 Date start
    .col-sm-2.col-md-3
      .form-group
        = select_month event.started_at, {}, name: 'event[started_at(2i)]', class: 'form-control', data: { required: true, 'required-message' => 'Start month is empty', 'errors-container' => '.error-message' }
    .col-sm-2
      .form-group
        = select_day event.started_at, {}, name: 'event[started_at(3i)]', class: 'form-control', data: {required: true, dateLower: '{ "start": "#date-start", "end": "#date-end" }', 'dateLower-message' => 'Start date must be lower than finish date', 'errors-container' => '.error-message'}
    .col-sm-2.col-md-3
      .form-group
        = select_year event.started_at, { start_year: Award.start_year, end_year: Award.end_year }, name: 'event[started_at(1i)]', class: 'form-control', data: { required: true, 'errors-messages-disabled' => true, 'errors-container' => '.error-message' }
    .error-message
  .row#date-end
    .col-sm-2
      p.text-color.p-t7 Date end
    .col-sm-2.col-md-3
      .form-group
        = select_month event.finished_at, {}, name: 'event[finished_at(2i)]', class: 'form-control', data: { required: true, 'required-message' => 'Start month is empty', 'errors-container' => '.error-message' }
    .col-sm-2
      .form-group
        = select_day event.finished_at, {}, name: 'event[finished_at(3i)]', class: 'form-control', data: {required: true, 'required-message' => 'Start month is empty', 'errors-container' => '.error-message'}
    .col-sm-2.col-md-3
      .form-group
        = select_year event.finished_at, { start_year: Award.start_year, end_year: Award.end_year }, name: 'event[finished_at(1i)]', class: 'form-control', data: { required: true, 'required-message' => 'Start month is empty', 'errors-container' => '.error-message' }
  .row
    .col-sm-2
      p.text-color.p-t7 Price / USD
    .col-sm-2
      = form.input :price, as: :string, input_html: { class: 'form-control', data: { required: true } }, wrapper_html: { class: 'has-down-error' }
  .row
    .col-xs-12.m-b20
      button.btn.btn-primary.pull-right Submit
= render 'base/private/events/blocks/progress'
= render 'base/blocks/private/crop'
- javascript 'controllers/base/event/new'

app/views/base/private/events/blocks/_progress.html.slim
.hidden#crop-progress
  .shadow
  .crop
    .crop_progress
      .countBar 0%
      .lineBar data-value="0"
        .progressBar

app/views/base/private/events/blocks/_status.html.slim
.galleryStatus
  i class="icon-#{status}"
  p class="galleryStatus_#{status}"
    = status